server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_database
    username: root
    password: YKDahiya#1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: dk4750880@gmail.com
    password: ulrdurgkorpociid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true